resource "local_sensitive_file" "ssh_private_key" {
  filename = "${path.module}/autogenerated/id_rsa"
  content  = tls_private_key.ssh_key.private_key_pem
}

resource "local_sensitive_file" "ssh_public_key" {
  filename = "${path.module}/autogenerated/id_rsa.pub"
  content  = tls_private_key.ssh_key.public_key_openssh
}

resource "tls_private_key" "ssh_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}